---
name: Integration tests on Azure
on:  # yamllint disable-line rule:truthy

  pull_request:
    branches:
      - v*

jobs:
  integration-tests-azure:
    name: Integration tests on Azure
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python_version: ["3.11"]
        msodbc_version: ["18"]
        # disabling as overkill (for now)
        # python_version: ["3.8", "3.9", "3.10", "3.11"]
        # msodbc_version: ["17", "18"]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
      pull-requests: write
      security-events: write
    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-${{ matrix.python_version }}-msodbc${{ matrix.msodbc_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r dev_requirements.txt

      - name: Run functional tests
        env:
          DBT_SYNAPSE_SERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}
          DBT_SYNAPSE_DB: ${{ secrets.DBT_SYNAPSE_DB }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
          DBT_TEST_USER_1: DBT_TEST_USER_1
          DBT_TEST_USER_2: DBT_TEST_USER_2
          DBT_TEST_USER_3: DBT_TEST_USER_3
          SYNAPSE_TEST_DRIVER: 'ODBC Driver ${{ matrix.msodbc_version }} for SQL Server'
        run: pytest -r a -vv -x tests/functional --profile "ci_azure_auto"
